spring:
  cloud:
    gateway:
      routes:
      # 登录路由，不验证token
      - id: login_route
        uri: http://10.1.7.81:8081
        predicates:
        - Path=/gateway/login/**
        filters:
        - StripPrefix=1
      - id: server_route
        # 转发地址
        uri: http://10.1.7.81:8081
        predicates:
        # 拦截请求路径
        - Path=/gateway/**
        filters:
        # 跳过1个前缀
        - StripPrefix=1
        # token身份认证 JwtCheckGatewayFilterFactory
#        - TokenCheck
        # 请求流量限制，默认5MB
        - name: RequestSize
          args:
            maxSize: 5000000
      # sockJS路由需要与websocket路由结合使用
      - id: sockJS_route
        uri: http://10.1.7.81:8081
        predicates:
          - Path=/websocket/**
      - id: websocket_route
        uri: ws://localhost:8081
        predicates:
          - Path=/websocket/**
      # 开启/关闭网关
      enabled: true
      loadbalancer:
        use404: true
  application:
    name: gateway